.TH "FormsPixelEngine.FPE.Sound.AudioClip" 3 "Tue Feb 14 2023" "Version 0.1.0" "FromsPixelEngin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FormsPixelEngine.FPE.Sound.AudioClip
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAudioClip\fP (string _filename)"
.br
.ti -1c
.RI "void \fBPlay\fP ()"
.br
.ti -1c
.RI "void \fBPlayLoop\fP ()"
.br
.ti -1c
.RI "void \fBStop\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for FromsPixelEngin from the source code\&.
