.TH "FormsPixelEngine.FPE.Rendering.Sprites" 3 "Tue Feb 14 2023" "Version 0.1.0" "FromsPixelEngin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FormsPixelEngine.FPE.Rendering.Sprites
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSprite\fP"
.br
.RI "Represents a generic sprite\&. "
.ti -1c
.RI "class \fBTextureSprite\fP"
.br
.RI "Represents a sprite loaded from a texture file\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for FromsPixelEngin from the source code\&.
