.TH "FormsPixelEngine.FPE.Rendering.Sprites.Sprite" 3 "Tue Feb 14 2023" "Version 0.1.0" "FromsPixelEngin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FormsPixelEngine.FPE.Rendering.Sprites.Sprite \- Represents a generic sprite\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "abstract uint[] \fBGetPixelData\fP ()"
.br
.RI "Returns the image data\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "abstract uint \fBWidth\fP\fC [get]\fP"
.br
.RI "Width of the Sprite\&. "
.ti -1c
.RI "abstract uint \fBHeight\fP\fC [get]\fP"
.br
.RI "Height of the Sprite\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents a generic sprite\&. 

This abstract class represents a generic sprite\&. It holds an array of Pixels, the Width and Height of a Sprite 
.SH "Member Function Documentation"
.PP 
.SS "abstract uint[] FormsPixelEngine\&.FPE\&.Rendering\&.Sprites\&.Sprite\&.GetPixelData ()\fC [pure virtual]\fP"

.PP
Returns the image data\&. 
.PP
\fBReturns\fP
.RS 4
Array of unsigned Integers that represent the image pixel data\&. 
.RE
.PP

.PP
Implemented in \fBFormsPixelEngine\&.FPE\&.Rendering\&.Sprites\&.TextureSprite\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FromsPixelEngin from the source code\&.
