.TH "FormsPixelEngine.FPE.Scene.SceneManager" 3 "Tue Feb 14 2023" "Version 0.1.0" "FromsPixelEngin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FormsPixelEngine.FPE.Scene.SceneManager
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSceneManager\fP (\fBRenderer\fP _renderer, \fBInputSystem\fP _input)"
.br
.ti -1c
.RI "void \fBSetScene\fP (\fBScene\fP _scene)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBScene\fP? \fBcurrentScene\fP\fC [get]\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for FromsPixelEngin from the source code\&.
