.TH "FormsPixelEngine.FPE.Rendering.Camera" 3 "Tue Feb 14 2023" "Version 0.1.0" "FromsPixelEngin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FormsPixelEngine.FPE.Rendering.Camera \- Represents a camera\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCamera\fP (float _x, float _y)"
.br
.RI "Constructor of Camera\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents a camera\&. 

This class defines a camera and is used by the renderer\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FormsPixelEngine\&.FPE\&.Rendering\&.Camera\&.Camera (float _x, float _y)"

.PP
Constructor of Camera\&. 
.PP
\fBParameters\fP
.RS 4
\fI_x\fP Camera x position\&. 
.br
\fI_x\fP Camera y position\&. 
.RE
.PP
\fBSee also\fP
.RS 4
Renderer\&.PushCamera 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for FromsPixelEngin from the source code\&.
