.TH "FormsPixelEngine.FPE.Rendering" 3 "Tue Feb 14 2023" "Version 0.1.0" "FromsPixelEngin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FormsPixelEngine.FPE.Rendering
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCamera\fP"
.br
.RI "Represents a camera\&. "
.ti -1c
.RI "class \fBRenderer\fP"
.br
.RI "Renders to the Window\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for FromsPixelEngin from the source code\&.
