.TH "FormsPixelEngine.FPE.Rendering.Text" 3 "Tue Feb 14 2023" "Version 0.1.0" "FromsPixelEngin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FormsPixelEngine.FPE.Rendering.Text
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCharData\fP"
.br
.RI "Represents the character information for text rendering\&. "
.ti -1c
.RI "class \fBFPEFont\fP"
.br
.RI "Represents a font and is used for text rendering\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for FromsPixelEngin from the source code\&.
