.TH "FormsPixelEngine.FPE.Rendering.Text.CharData" 3 "Tue Feb 14 2023" "Version 0.1.0" "FromsPixelEngin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FormsPixelEngine.FPE.Rendering.Text.CharData \- Represents the character information for text rendering\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBorg\fP"
.br
.ti -1c
.RI "uint \fBwidth\fP"
.br
.ti -1c
.RI "uint \fBheight\fP"
.br
.ti -1c
.RI "uint[] \fBpixelData\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents the character information for text rendering\&. 

This class holds the width, hight and pixel data for the rendering of Text 

.SH "Author"
.PP 
Generated automatically by Doxygen for FromsPixelEngin from the source code\&.
