.TH "FormsPixelEngine.FPE.Scene.Scene" 3 "Tue Feb 14 2023" "Version 0.1.0" "FromsPixelEngin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FormsPixelEngine.FPE.Scene.Scene
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInitScene\fP (\fBRenderer\fP _renderer, \fBInputSystem\fP _input, \fBSceneManager\fP _sceneManager)"
.br
.ti -1c
.RI "void \fBUpdateScene\fP (float _deltatime)"
.br
.ti -1c
.RI "abstract void \fBInit\fP ()"
.br
.ti -1c
.RI "abstract void \fBUpdate\fP ()"
.br
.ti -1c
.RI "abstract void \fBClose\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBRenderer\fP \fBrenderer\fP"
.br
.ti -1c
.RI "\fBInputSystem\fP \fBinput\fP"
.br
.ti -1c
.RI "\fBSceneManager\fP \fBsceneManager\fP"
.br
.ti -1c
.RI "float \fBdeltaTime\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for FromsPixelEngin from the source code\&.
